[book]
authors = ["Natalia Cholewa"]
language = "en"
multilingual = false
src = "src"
title = "A Comprehensive Guide To UEFI Programming"

[output.html]
git-repository-url = "https://github.com/natanalt/uefi-guide"
