name: Deploy the book
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website contents
        uses: actions/checkout@v3

      - name: Cache mdbook
        uses: actions/cache@v3
        with:
          key: mdbook-cache
          path: ~/.cargo/bin/mdbook

      - name: Install mdbook
        run: cargo install mdbook

      - name: Build the book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: book
